KatsuteDev/Mal4J

- src/main/java/com/kttdevelopment/myanimelist/APICall.java
- src/main/java/com/kttdevelopment/myanimelist/Json.java
- src/main/java/com/kttdevelopment/myanimelist/MyAnimeListImpl.java
- src/main/java/com/kttdevelopment/myanimelist/MyAnimeListService.java
- src/main/java/com/kttdevelopment/myanimelist/query/AnimeListUpdate.java
- src/main/java/com/kttdevelopment/myanimelist/query/AnimeRankingQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/AnimeSearchQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/AnimeSeasonQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/AnimeSuggestionQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/FieldSearchQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/ForumSearchQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/ListUpdate.java
- src/main/java/com/kttdevelopment/myanimelist/query/MangaListUpdate.java
- src/main/java/com/kttdevelopment/myanimelist/query/MangaRankingQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/MangaSearchQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/SearchQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/UserAnimeListQuery.java
- src/main/java/com/kttdevelopment/myanimelist/query/UserMangaListQuery.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnimeSearch.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnimeSeason.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnimeSuggestions.java
- src/test/java/com/kttdevelopment/myanimelist/MangaTests/TestMangaSearch.java
- src/test/java/com/kttdevelopment/myanimelist/TestIterator.java
- src/test/java/com/kttdevelopment/myanimelist/TestJson.java
- Fixed issue where queries would return a preview instead of the full object.
- Fixed #28 pagination now only uses 1 call.
- Fixed issue where certain search queries were still using unoptimized 3 request search.
- Fixed critical issue where pagination would not work unless limit was supplied (now uses 100 default as stipulated by the API).
- Fixed #32
> Query optimizations, JSON slash fixes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/error_report.md
- README.md
- docs/_data/nav.yml
- docs/faq.md
- docs/features.md
- src/main/java/com/kttdevelopment/myanimelist/MyAnimeList.java
- src/main/java/com/kttdevelopment/myanimelist/MyAnimeListImpl.java
- src/main/java/com/kttdevelopment/myanimelist/query/FieldSearchQuery.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnime.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnimeListStatus.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnimeRank.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnimeSearch.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestAnimeSeason.java
- src/test/java/com/kttdevelopment/myanimelist/AnimeTests/TestUserAnimeListing.java
- src/test/java/com/kttdevelopment/myanimelist/MangaTests/TestManga.java
- src/test/java/com/kttdevelopment/myanimelist/MangaTests/TestMangaListStatus.java
- src/test/java/com/kttdevelopment/myanimelist/MangaTests/TestMangaRank.java
- src/test/java/com/kttdevelopment/myanimelist/MangaTests/TestMangaSearch.java
- src/test/java/com/kttdevelopment/myanimelist/MangaTests/TestUserMangaListing.java
- src/test/java/com/kttdevelopment/myanimelist/UserTests/TestUser.java
By default the API will now return the bare minimum fields instead of all fields. This is in order to match the MAL API documentation.
- Closes #34 
- Minor bug fixes regarding fields
- Adds static ALL fields
- Clarifies documentation for field parameter
- Closes #36
> Have no fields return default fields

- .gitignore
- README.md
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
- src/main/java/com/kttdevelopment/mal4j/query/FieldSearchQuery.java
- src/main/java/com/kttdevelopment/mal4j/user/User.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeRank.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSearch.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSeason.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestUserAnimeListing.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaRank.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaSearch.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestUserMangaListing.java
- src/test/java/com/kttdevelopment/mal4j/TestAuthRefresh.java
- src/test/java/com/kttdevelopment/mal4j/TestIterator.java
- src/test/java/com/kttdevelopment/mal4j/TestProvider.java
- src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java
**Major Changes:**
- All fields now returned by default (null is treated as all)
- Two new methods for FieldQuery
- `#withAllFields` - includes all fields (null)
- `#withNoFields` - includes only default fields (uses static `NO_FIELDS`)
- ⚠client.txt / oauth.txt has been moved to `src/test/java/resources`
- Added method to get user birthday as a Date
**Minor Changes:**
- Test repairs
- Documentation reordering
- Renamed string list method to comma separated string
- Additional fixes to make method compatible with null to all change
- Minior test provider changes
> API returns ALL FIELDS by default.

- README.md
- readme.bbcode
- src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java
- src/main/java/com/kttdevelopment/mal4j/anime/Anime.java
- src/main/java/com/kttdevelopment/mal4j/anime/property/EndingTheme.java
- src/main/java/com/kttdevelopment/mal4j/anime/property/OpeningTheme.java
- src/main/java/com/kttdevelopment/mal4j/anime/property/Theme.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
- src/test/java/com/kttdevelopment/mal4j/TestProvider.java
- Closes #88 
Adds op/eds to Anime.
Op/ed name returns only text because the format used is not consistent across all Anime.
> Add Opening/Ending to Anime

- src/main/java/module-info.java
Fixes missing export statement for `User.Property`
> Fix critical issue where UserRetrievable could not be accessed

- src/main/java/com/kttdevelopment/mal4j/manga/property/MangaType.java
Light novels should now correctly return `LightNovel` as the type (#126).
This pull deprecates the `Novel` enum as it is not used by MyAnimeList, it will be removed in a later release.
> Fixed Light novels having unknown type.

- src/main/java/com/kttdevelopment/mal4j/HttpException.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
Closes #129 
Fixed issue where HttpException didn't display exception message correctly.
> Fixed HttpException

- pom.xml
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
- src/main/java/com/kttdevelopment/mal4j/user/User.java
- src/test/java/com/kttdevelopment/mal4j/TestMyAnimeList.java
- src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java
> Closes #125 
Developers will now be able to access user Anime/Manga list statuses from the user object.
This update also shifts username enforcement to the server.
> Retrieve User Anime/Manga listings from User object.

- src/main/java/com/kttdevelopment/mal4j/AuthResponseHandler.java
- src/main/java/com/kttdevelopment/mal4j/Fields.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
- src/main/java/com/kttdevelopment/mal4j/query/FieldQuery.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
- src/test/java/com/kttdevelopment/mal4j/TestJava9.java
- src/test/java/com/kttdevelopment/mal4j/TestMyAnimeList.java
**Issue:** *The main issue(s) that this pull request fixes.*
#170 
https://github.com/Katsute/Mal4J/runs/2569301593
- Adds inverted fields (ability to return all except select fields)
- Adds inverted fields to query object
**Example usage:**
```java
MyAnimeList mal;
Anime anime = mal.get(13759, Fields.Anime.episodes, Fields.INVERTED);
anime.getEpisodes(); // would be null because fields are inverted
anime.getRating(); // would not be null because ratings field was not part of supplied parameter
```
> Add inverted fields

- .github/workflows/release.yml
Manually created because dependabot fails to notice that a new version is available.
Replaces #176
> Bump crazy-max/ghaction-import-gpg from 3 to 3.1.0

- pom.xml
Bumps JUnit from 5.7.1 to 5.7.2
- Mainly bugfixes
[Full changelog](https://junit.org/junit5/docs/5.7.2/release-notes/)
> Bump org.junit.jupiter from 5.7.1 to 5.7.2

- src/main/java/com/kttdevelopment/mal4j/APICall.java
- src/main/java/com/kttdevelopment/mal4j/InvalidTokenException.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
- src/main/java/com/kttdevelopment/mal4j/query/LimitOffsetQuery.java
- src/test/java/com/kttdevelopment/mal4j/TestGenre.java
- src/test/java/com/kttdevelopment/mal4j/TestMyAnimeList.java
https://github.com/Katsute/Mal4J/actions/runs/1117529501
- added exception for invalid or expired token
> Add exception for invalid or expired token

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/mal_ci.yml
- README.md
- faq.md
- readme.bbcode
- setup.md
- src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListService.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSuggestions.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestUserAnimeListing.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
- src/test/java/com/kttdevelopment/mal4j/MangaTests/TestUserMangaListing.java
- src/test/java/com/kttdevelopment/mal4j/TestAuthorizationLocalServer.java
- src/test/java/com/kttdevelopment/mal4j/TestMyAnimeList.java
- src/test/java/com/kttdevelopment/mal4j/TestProvider.java
- src/test/java/com/kttdevelopment/mal4j/TestREADME.java
- src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java
https://github.com/Katsute/Mal4J/actions/runs/1478373853
- Add ability to authenticate with client ID only #256
- Throw exception on write operations when there is no token
- Change `MyAnimeList.withOAuthToken(String)` to `MyAnimeList.withToken(String)`
- [DEPRECATED] Deprecate `MyAnimeList.withOAuthToken(String)`
- Change `MyAnimeList.refreshOAuthToken()` to `MyAnimeList.refreshToken()`
- [DEPRECATED] Deprecate `MyAnimeList.refreshOAuthToken()`
- [TESTS] Update test matrix to run client and token tests
- [TESTS] Update MAL test provider
- [TESTS] SKIP write/private tests on client tests
- [TESTS] …
> Ability to authenticate using client ID

- pom.xml
- src/main/java/com/kttdevelopment/mal4j/PaginatedIterator.java
- src/test/java/com/kttdevelopment/mal4j/TestIterator.java
- Made paginated iterator toList return a new list instead of an unmodifiable one.
- Made paginated iterator toSet return a new set instead of an unmodifiable one.
- Documentation changes.
- Test changes.
[WF-2981809091](https://github.com/KatsuteDev/Mal4J/actions/runs/2981809091)
> Paginated iterator now returns a modifiable list instead of an unmodifiable one

- src/main/java/com/kttdevelopment/mal4j/anime/property/AnimeSource.java
- src/main/java/com/kttdevelopment/mal4j/manga/property/MangaType.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
- Removed AnimeSource.Web_Manga
- Removed AnimeSource.Digital_Manga
- Removed MangaType.Novel
- Removed `AnimeSource.Web_Manga`, use `AnimeSource.WebManga`
- Removed `AnimeSource.Digital_Manga`, use `AnimeSource.DigitalManga`
- Removed `MangaType.Novel`, use `MangaType.LightNovel`
> Removed deprecated enums

- pom.xml
- src/main/java/com/kttdevelopment/mal4j/ExperimentalFeatureException.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
- src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
- src/test/java/com/kttdevelopment/mal4j/TestExperimentalEnabler.java
- src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java
- Throw exception if experimental feature is used without enabling
[WF-3109844729](https://github.com/KatsuteDev/Mal4J/actions/runs/3109844729)
* Using an experimental feature without enabling it will throw a `ExperimentalFeatureException`, previously would only print a warning
> Using experimental features without enabling them will now throw an exception

- pom.xml
- src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
- src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
- Removed deprecated auth methods
[WF-3107700449](https://github.com/KatsuteDev/Mal4J/actions/runs/3107700449)
* Removed `withOAuthToken`, use `withToken`
* Removed `refreshOAuthToken`, use `refreshToken`
* Removed `withAuthorization`, use `withOAuth2`
* The deprecated String parameter has been replaced with the Authorization parameter.
Previously:
```java
new MyAnimeListAuthenticator("client_id", "client_secret", "authorization_code", "PKCE_code_challenge");
```
Should be replaced with:
```java
new MyAnimeListAuthenticator(new Authorization("client_id", "client_secret", "authorization_code", "PKCE_code_challenge")); …
```
> Remove deprecated authentication methods

- pom.xml
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema.java
- src/test/java/dev/katsute/mal4j/TestDateTime.java
- src/test/java/dev/katsute/mal4j/TestExperimentalEnabler.java
- src/test/java/dev/katsute/mal4j/TestJson.java
- src/test/java/dev/katsute/mal4j/TestREADME.java
- Fix parsing failures on incomplete dates
[WF-3907690947](https://github.com/KatsuteDev/Mal4J/actions/runs/3907690947)
> Fix NullableDate

- pom.xml
- src/main/java/dev/katsute/mal4j/Json.java
- src/main/java/dev/katsute/mal4j/MyAnimeListAuthenticator.java
- src/main/java/dev/katsute/mal4j/MyAnimeListImpl.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Anime.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Common.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Forum.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Manga.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_User.java
- src/test/java/dev/katsute/mal4j/AnimeTests/TestAnime.java
- src/test/java/dev/katsute/mal4j/ForumTests/TestForumCategories.java
- src/test/java/dev/katsute/mal4j/ForumTests/TestForumTopicDetail.java
- src/test/java/dev/katsute/mal4j/MangaTests/TestManga.java
- src/test/java/dev/katsute/mal4j/TestExperimentalEnabler.java
- src/test/java/dev/katsute/mal4j/TestJson.java
- src/test/java/dev/katsute/mal4j/TestPreview.java
- src/test/java/dev/katsute/mal4j/UserTests/TestUser.java
- Closes #362
- Return nullable numbers instead of primitive
- Make boolean parsing more specific
- Return jsonobject for null objects
- Fix null on arrays
- Remove use of lambdas
[WF-4146586281](https://github.com/KatsuteDev/Mal4J/actions/runs/4146586281)
> Parsing optimizations

- src/main/java/dev/katsute/mal4j/Json.java
- src/test/java/dev/katsute/mal4j/MangaTests/TestMangaListStatus.java
- Use json optimizations from https://github.com/KatsuteDev/OneMTA/blob/f6c82a376dcd98b1a77ed9cd3e6bf04ee098ffd5/src/main/java/dev/katsute/onemta/Json.java
- Replaces regex parsing with character-by-character parsing
[WF-4168613316](https://github.com/KatsuteDev/Mal4J/actions/runs/4168613316)
This library is now 70% faster after this change.
> JSON optimizations

- README.md
- pom.xml
- readme.bbcode
- src/main/java/dev/katsute/mal4j/Fields.java
- src/main/java/dev/katsute/mal4j/MyAnimeList.java
- src/main/java/dev/katsute/mal4j/MyAnimeListImpl.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Character.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_People.java
- src/main/java/dev/katsute/mal4j/MyAnimeListService.java
- src/main/java/dev/katsute/mal4j/people/Person.java
- src/main/java/dev/katsute/mal4j/people/package-info.java
- src/main/java/dev/katsute/mal4j/property/ExperimentalFeature.java
- src/main/java11/module-info.java
- src/main/java9/module-info.java
- src/test/java/dev/katsute/mal4j/PeopleTests/TestPeople.java
- src/test/java/dev/katsute/mal4j/TestProvider.java
- src/test/java/dev/katsute/mal4j/TestREADME.java
- Added person endpoint
https://github.com/KatsuteDev/Mal4J/actions/runs/5072826144
This is an undocumented feature, you must use `MyAnimeList.enableExperimentalFeature(ExperimentalFeature.PEOPLE)` to enable it.
Retrieve people using `MyAnimeList.getPerson(id)`.
Person information currently includes:
* Name
* Birthday
* Picture
> Add people support

- pom.xml
- src/main/java/dev/katsute/mal4j/Fields.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Character.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Common.java
- src/main/java/dev/katsute/mal4j/MyAnimeListSchema_People.java
- src/main/java/dev/katsute/mal4j/character/Character.java
- src/main/java/dev/katsute/mal4j/people/Person.java
- src/test/java/dev/katsute/mal4j/CharacterTests/TestCharacter.java
- src/test/java/dev/katsute/mal4j/PeopleTests/TestPeople.java
- Add missing fields #392
- Coerce biography to map
https://github.com/KatsuteDev/Mal4J/actions/runs/5135268260
* Add favorites count to character and people
* Add alternative names and 'more' field to people
* Add method to retrieve character biography details as a map
> Add missing character and people fields

- pom.xml
- src/main/java/dev/katsute/mal4j/Logging.java
- src/main/java/dev/katsute/mal4j/MyAnimeListImpl.java
- src/test/java/dev/katsute/mal4j/AnimeTests/TestUserAnimeListing.java
- src/test/java/dev/katsute/mal4j/MangaTests/TestUserMangaListing.java
- Preload next page into iterator to check if there is actually more items
- Fix status test case
https://github.com/KatsuteDev/Mal4J/actions/runs/6511183467
> Fix IndexOutOfBoundsException when using an iterator
