src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListService.java
src/main/java/com/kttdevelopment/mal4j/query/ListUpdate.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java

- Added ability to set `start_date` and `finish_date` on list statuses
- Fixed missing `finish_date` on Anime list statuses
- ~~Made date format static final~~

Add `start_date` and `finish_date` to list update.

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSuggestionQuery.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSeason.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java

Removes internal checks on parameters, this field is checked by the server-side API.
- Fixes #56 
- Closes #53

Move parameter enforcement to server-side

---

src/main/java/com/kttdevelopment/mal4j/HTTPException.java
src/main/java/com/kttdevelopment/mal4j/HttpException.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/query/SearchQuery.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java

Allow soft failures for delete.

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java
src/main/java/com/kttdevelopment/mal4j/forum/ForumTopicDetail.java
src/main/java/com/kttdevelopment/mal4j/forum/Post.java
src/main/java/com/kttdevelopment/mal4j/property/ListStatus.java
src/main/java/com/kttdevelopment/mal4j/property/MediaItem.java
src/main/java/com/kttdevelopment/mal4j/user/User.java
src/main/java/com/kttdevelopment/mal4j/user/UserMangaStatistics.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/ForumTests/TestForumTopics.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java

- Fix #67 (redundant dates)
- Fix #68 (typo)
- Fix #69 (missing dates)

🐞 Bug Fixes

---

src/main/java/com/kttdevelopment/mal4j/AccessToken.java
src/test/java/com/kttdevelopment/mal4j/TestAuthRefresh.java

**Changes:**
- Closes #77 (date/expiry methods)
- Fixed issue where expiry would not change
- Added test cases

Access Token changes

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeRankingQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSeasonQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSuggestionQuery.java
src/main/java/com/kttdevelopment/mal4j/query/FieldQuery.java
src/main/java/com/kttdevelopment/mal4j/query/ForumSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/LimitOffsetQuery.java
src/main/java/com/kttdevelopment/mal4j/query/MangaRankingQuery.java
src/main/java/com/kttdevelopment/mal4j/query/MangaSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/SearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/UserAnimeListQuery.java
src/main/java/com/kttdevelopment/mal4j/query/UserMangaListQuery.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java

Query Optimizations

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListService.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeRankingQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSeasonQuery.java
src/main/java/com/kttdevelopment/mal4j/query/UserAnimeListQuery.java
src/main/java/com/kttdevelopment/mal4j/query/UserMangaListQuery.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSearch.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSeason.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
src/test/java/com/kttdevelopment/mal4j/TestProvider.java

- Closes #81 
Anime/manga list now accepts NSFW parameter. Currently causing some issues (see #90)
- Closes #5 
Recent change has also added NSFW parameter back to seasonal and ranking queries

Fix NSFW Issues

---

faq.md
src/main/java/com/kttdevelopment/mal4j/query/AnimeListUpdate.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeRankingQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSeasonQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSuggestionQuery.java
src/main/java/com/kttdevelopment/mal4j/query/MangaRankingQuery.java
src/main/java/com/kttdevelopment/mal4j/query/MangaSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/NSFW.java
src/main/java/com/kttdevelopment/mal4j/query/NSFWSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/UserAnimeListQuery.java
src/main/java/com/kttdevelopment/mal4j/query/UserMangaListQuery.java
src/test/java/com/kttdevelopment/mal4j/TestProvider.java

Optimize NSFW query

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/UnauthorizedAccessException.java
src/main/java/com/kttdevelopment/mal4j/anime/property/EndingTheme.java
src/main/java/com/kttdevelopment/mal4j/anime/property/OpeningTheme.java
src/main/java/com/kttdevelopment/mal4j/anime/property/Theme.java
src/main/java/com/kttdevelopment/mal4j/query/NSFW.java
src/main/java/com/kttdevelopment/mal4j/query/NSFWSearchQuery.java

Fixes some missing documentation tags.

Minor sourcecode/documentation fixes

---

src/main/java/com/kttdevelopment/mal4j/Json.java
src/test/java/com/kttdevelopment/mal4j/TestJson.java

> Closes #94 
Fixed issue where Json parser would fail if the response had newlines.

Fixed newline Json issue.

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/query/FieldQuery.java
src/main/java/com/kttdevelopment/mal4j/query/ListUpdate.java
src/test/java/com/kttdevelopment/mal4j/TestAuthorization.java
src/test/java/com/kttdevelopment/mal4j/TestMyAnimeList.java

> Closes #113 
Adds more helpful error messages for:
- MyAnimeList
- MyAnimeListAuthenticator
Fixes:
- Null field issue
- Null tag issue

Add more helpful error messages

---

src/main/java/com/kttdevelopment/mal4j/PaginatedIterator.java

Closes #119 
`index++` → `++index`

Optimize PaginatedIterator

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
README.md
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeRank.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaRank.java
src/test/java/com/kttdevelopment/mal4j/TestProvider.java
src/test/java/com/kttdevelopment/mal4j/TestREADME.java

- Fixes #115 
- Updates contribution guidelines
- Updates pull request requirements
- Adds additional test cases
- Fixes existing test cases
- Optimizes existing test cases

Fix test cases & update pull requirements

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/PaginatedIterator.java
src/test/java/com/kttdevelopment/mal4j/TestIterator.java

- Fixed issue where list would initially be empty.
- Fixed critical issue where MyAnimeList would return incorrect offset url causing items to be skipped.
- Minor optimizations.

Fixed PaginatedIterator

---

.github/workflows/java_ci.yml
.github/workflows/mal_ci.yml
pom.xml
src/main/java/com/kttdevelopment/mal4j/APICall.java
src/main/java/com/kttdevelopment/mal4j/Json.java

Closes #133.
Fixes issue where android would not parse acceptable regex syntax.
[CI](https://github.com/Katsute/Mal4J/actions/runs/658980597)

Fix issue where android would not parse regex correctly

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java

Removes static fields from `MyAnimeList` class. Use `Fields` class for these fields instead.

Remove deprecated fields.

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/Json.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListService.java
src/main/java/com/kttdevelopment/mal4j/query/FieldQuery.java
src/main/java/com/kttdevelopment/mal4j/query/LimitOffsetQuery.java
src/main/java/com/kttdevelopment/mal4j/query/ListUpdate.java
src/main/java/com/kttdevelopment/mal4j/query/NSFW.java
src/main/java/com/kttdevelopment/mal4j/query/NSFWSearchQuery.java

- Fix some style issues.
- Remove unused documentation.

Cleanup documentation.

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/forum/ForumTopic.java
src/main/java/com/kttdevelopment/mal4j/forum/ForumTopicDetail.java
src/main/java/com/kttdevelopment/mal4j/query/ForumSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/ForumTopicDetailPostQuery.java
src/test/java/com/kttdevelopment/mal4j/ForumTests/TestForumTopics.java
src/test/java/com/kttdevelopment/mal4j/TestIterator.java

Closes #83 
- Added `ForumTopicDetailPostQuery` to `MyAnimeList`
- Added `getID()` to `ForumTopicDetail`
- Added `getBoardID()` to `ForumTopic`
- Added `getSubBoardID()` to `ForumTopic`

Add post iterator for ForumTopicDetail; Added additional ID methods to forum objects.

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/APICall.java

**Issue:** #154 
**Workflow Run:** https://github.com/Katsute/Mal4J/actions/runs/720246993
- Fixes #154

Fix Android reflection issue.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/workflows/javadoc.yml
README.md
faq.md
src/main/java/com/kttdevelopment/mal4j/APICall.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/anime/property/package-info.java
src/main/java/com/kttdevelopment/mal4j/anime/property/time/Season.java
src/main/java/com/kttdevelopment/mal4j/anime/property/time/Time.java
src/main/java/com/kttdevelopment/mal4j/forum/ForumBoard.java
src/main/java/com/kttdevelopment/mal4j/forum/ForumCategory.java
src/main/java/com/kttdevelopment/mal4j/forum/ForumTopic.java
src/main/java/com/kttdevelopment/mal4j/forum/ForumTopicDetail.java
src/main/java/com/kttdevelopment/mal4j/forum/property/PostAuthor.java
src/main/java/com/kttdevelopment/mal4j/manga/property/MangaType.java
src/main/java/com/kttdevelopment/mal4j/property/RankingType.java
src/main/java/com/kttdevelopment/mal4j/query/UserAnimeListQuery.java
src/main/java/com/kttdevelopment/mal4j/query/UserMangaListQuery.java
src/main/java11/module-info.java
src/main/java9/module-info.java

**Issue:** #157 
**Workflow Run:** https://github.com/Katsute/Mal4J/actions/runs/750190975
- Fix issue where seasons month array could be modified.

Improve documentation

---

src/main/java/com/kttdevelopment/mal4j/Json.java
src/test/java/com/kttdevelopment/mal4j/TestJson.java

**Issue:** #156 
**Workflow Run:** https://github.com/Katsute/Mal4J/actions/runs/749692005
- Closes #156 
- Adds method to retrieve raw json

Improve JsonSyntaxException

---

README.md
pom.xml
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeRank.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSeason.java
src/test/java/com/kttdevelopment/mal4j/ForumTests/TestForumCategories.java
src/test/java/com/kttdevelopment/mal4j/ForumTests/TestForumTopicDetail.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaRank.java
src/test/java/com/kttdevelopment/mal4j/TestGenre.java
src/test/java/com/kttdevelopment/mal4j/TestJava9.java
src/test/java/com/kttdevelopment/mal4j/TestJson.java
src/test/java/com/kttdevelopment/mal4j/TestProvider.java
src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java

**Issue:** *The main issue(s) that this pull request fixes.*
None
https://github.com/Katsute/Mal4J/actions/runs/821624960
- Update to Junit 5.7.1
- Convert to parameterized test cases

Test Improvements

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeListAPIResponseMapping.java

**Issue:** *The main issue(s) that this pull request fixes.*
None
https://github.com/Katsute/Mal4J/actions/runs/824169973
- Fixes issue where returned objects could have their arrays modified.

Fix array manipulation issue

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/user/User.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java

https://github.com/Katsute/Mal4J/actions/runs/837480979
- Add `MyAnimeList#getAuthenticatedUser`
- Deprecate `MyAnimeList#getMyself`

Replace `MyAnimeList#getMyself` with `MyAnimeList#getAuthenticatedUser`

---

src/main/java/com/kttdevelopment/mal4j/APICall.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_Anime.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_Common.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_Forum.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_Manga.java
src/main/java/com/kttdevelopment/mal4j/anime/property/time/Season.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestUserAnimeListing.java

https://github.com/Katsute/Mal4J/actions/runs/901228109
- Fixes some array copy issues.
- Fixes #184

Fix compatibility issue with Android API 28+ (9+)

---

README.md
pom.xml
src/main/java/com/kttdevelopment/mal4j/Fields.java

- Makes `Field` constructors private.

Make `Field` constructors private

---

src/main/java/com/kttdevelopment/mal4j/HttpException.java
src/main/java/com/kttdevelopment/mal4j/JsonSyntaxException.java
src/main/java/com/kttdevelopment/mal4j/UnauthorizedAccessException.java

Make exceptions final

---

.github/ISSUE_TEMPLATE/bug_report.md
faq.md
src/main/java/com/kttdevelopment/mal4j/APICall.java
src/main/java/com/kttdevelopment/mal4j/AndroidCompatibilityException.java

https://github.com/Katsute/Mal4J/actions/runs/954918649
- Fixed `methods` compatibility issue with Android API 1-12 (1-3.1)
- Fixed `modifiers` compatibility issue with Android API 18-25 (4.3-7.1.2)
- Added `AndroidCompatibilityException`

Fix Android compatibility issues

---

README.md
readme.bbcode
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSearchQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSeasonQuery.java
src/main/java/com/kttdevelopment/mal4j/query/AnimeSuggestionQuery.java
src/main/java/com/kttdevelopment/mal4j/query/MangaSearchQuery.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSearch.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSeason.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSuggestions.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaSearch.java
src/test/java/com/kttdevelopment/mal4j/TestIterator.java
src/test/java/com/kttdevelopment/mal4j/TestProvider.java
src/test/java/com/kttdevelopment/mal4j/TestREADME.java

https://github.com/Katsute/Mal4J/actions/runs/955542812
**This is a breaking change, existing query code will fail upon update**
- Fix issue where op/ed was expected from search queries even though it is not returned #196 
- Change queries so they return preview type instead of full type
- Adjust README to reflect change
- Add warning for debug mode

Fix queries not returning preview type

---

pom.xml
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeRank.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSearch.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSeason.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSuggestions.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestUserAnimeListing.java
src/test/java/com/kttdevelopment/mal4j/ForumTests/TestForumCategories.java
src/test/java/com/kttdevelopment/mal4j/ForumTests/TestForumTopicDetail.java
src/test/java/com/kttdevelopment/mal4j/ForumTests/TestForumTopics.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaRank.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaSearch.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestUserMangaListing.java
src/test/java/com/kttdevelopment/mal4j/TestAPICall.java
src/test/java/com/kttdevelopment/mal4j/TestAuthorization.java
src/test/java/com/kttdevelopment/mal4j/TestAuthorizationLocalServer.java
src/test/java/com/kttdevelopment/mal4j/TestGenre.java
src/test/java/com/kttdevelopment/mal4j/TestIterator.java
src/test/java/com/kttdevelopment/mal4j/TestJava9.java
src/test/java/com/kttdevelopment/mal4j/TestJson.java
src/test/java/com/kttdevelopment/mal4j/TestMyAnimeList.java
src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java

- updated jcore test dependency

Update jcore test dependency

---

faq.md
src/main/java/com/kttdevelopment/mal4j/APICall.java
src/main/java/com/kttdevelopment/mal4j/AndroidCompatibilityException.java
src/main/java/com/kttdevelopment/mal4j/Java9.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_User.java
src/main/java/com/kttdevelopment/mal4j/user/User.java
src/test/java/com/kttdevelopment/mal4j/UserTests/TestAffinityAlgorithm.java
src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java

https://github.com/Katsute/Mal4J/actions/runs/1117588533
- Optimize calls to self
- Implements #210

Add callback methods to Anime/Manga affinity

---

src/main/java/com/kttdevelopment/mal4j/property/RelationType.java

- Fix RelationType.toString() not returning the enum name.

Fix RelationType.toString()

---

.github/workflows/java_ci.yml
.github/workflows/javadoc.yml
.github/workflows/mal_ci.yml
.github/workflows/release.yml

Migrate to actions/setup-java

---

README.md
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatus.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatus.java

- https://github.com/Katsute/Mal4J/actions/runs/1187500223
- Adjust list tests to use non-zero values.

Adjust tests to use non-zero values.

---

src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeRank.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaRank.java
src/test/java/com/kttdevelopment/mal4j/UserTests/TestUser.java

https://github.com/Katsute/Mal4J/actions/runs/1199512836
- Adjust known external failures to be a warning
- Adjust bday warning message

(internal) adjust MAL external test failures

---

pom.xml

- #232 
- #233 
These dependencies can not be merged separately

Bump junit-jupiter-api and junit-jupiter-params from 5.7.2 to 5.8.0

---

.github/workflows/java_ci.yml
.github/workflows/javadoc.yml
.github/workflows/mal_ci.yml
.github/workflows/release.yml

- Add timeouts to all workflows

Enforce timeouts on workflows

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/Java9.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java

- Remove timestamp from experimental warning message
- Switch to using dedicated logger for all logging messages
- Adjust open browser warning

Adjust warning messages

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_Common.java
src/main/java/com/kttdevelopment/mal4j/query/NSFWSearchQuery.java

- Add missing toString for MyAnimeListAuthenticator
- Add missing override for NSFWQuery
- Fix missing hashcode on Genre

Code quality fixes

---

src/main/java/com/kttdevelopment/mal4j/APICall.java
src/main/java/com/kttdevelopment/mal4j/Java9.java
src/main/java/com/kttdevelopment/mal4j/Logging.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/test/java/com/kttdevelopment/mal4j/TestProvider.java

- Adjust connection debugging
- Add debug masking
- Allow devs to enable debug using `MyAnimeList.setDebug(boolean)`
- Move logging to dedicated class

Add debug mode

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_Anime.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListSchema_Manga.java

Fix Anime/Manga list ID sometimes being null

---

setup.md
src/main/java/com/kttdevelopment/mal4j/Java9.java
src/main/java/com/kttdevelopment/mal4j/Logging.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/manga/property/MangaStatistics.java
src/main/java/com/kttdevelopment/mal4j/user/property/MangaAffinity.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeListStatusUsername.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaListStatusUsername.java
src/test/java/com/kttdevelopment/mal4j/TestREADME.java

- Warn on use of deprecated classes/methods
- Cleanup annotations

Add warning when using deprecated classes/methods

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListAuthenticator.java
src/main/java/com/kttdevelopment/mal4j/query/LimitOffsetQuery.java

- Remove rare infrequent exceptions from documentation

Remove rare exceptions from documentation

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/Logging.java

- Fix issue where debug would log empty lines even when disabled

Fix random newlines appearing in log

---

src/main/java/com/kttdevelopment/mal4j/APICall.java

Removed unused code

---

pom.xml

- Fix missing `module-info.java` for Java 9/10

Fix modularity for Java 9-10

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/Logging.java
src/main/java/com/kttdevelopment/mal4j/anime/property/AnimeAirStatus.java
src/main/java/com/kttdevelopment/mal4j/anime/property/AnimeSource.java
src/main/java/com/kttdevelopment/mal4j/anime/property/AnimeType.java
src/main/java/com/kttdevelopment/mal4j/manga/property/MangaPublishStatus.java
src/main/java/com/kttdevelopment/mal4j/manga/property/MangaType.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnimeSearch.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestMangaSearch.java
src/test/java/com/kttdevelopment/mal4j/TestLogging.java

- Add missing Manga status OnHiatus
- Add missing Anime source MixedMedia, WebNovel
- Add missing Unknown type
- Rename Anime source Digital_Manga → DigitalManga
- Rename Anime source Web_Manga → WebManga
- Fallback to unknown rather than null
https://github.com/KatsuteDev/Mal4J/actions/runs/2449424775

Add missing hiatus, web novel, and mixed media enums

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/anime/property/AnimeSource.java

- Fix #314 
https://github.com/KatsuteDev/Mal4J/actions/runs/2477745325

Fix visual novel Anime source

---

.github/release.yml

Update configuration files

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/property/RelationType.java
src/test/java/com/kttdevelopment/mal4j/AnimeTests/TestAnime.java
src/test/java/com/kttdevelopment/mal4j/MangaTests/TestManga.java

- Add missing relation type 'spin off' and 'character'
- Return unknown relation type rather than null
[WF-2686336649](https://github.com/KatsuteDev/Mal4J/actions/runs/2686336649)
* Add missing relation type Spin off
* Add missing relation type Character
* For unknown relation type return Unknown rather than null

Add missing relation types

---

pom.xml
src/main/java/com/kttdevelopment/mal4j/anime/property/AnimeSource.java
src/main/java/com/kttdevelopment/mal4j/manga/property/MangaPublishStatus.java

[WF-2913089785](https://github.com/KatsuteDev/Mal4J/actions/runs/2913089785)
- Add missing MangaPublishingStatus `discontinued`

Add missing Manga publishing status `discontinued`

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeList.java
src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java

- Removed `MyAnimeList.getMySelf`
Use `MyAnimeList.getAuthenticatedUser`

Removed deprecated method MyAnimeList.getMyself

---

src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java
src/main/java/com/kttdevelopment/mal4j/property/ExperimentalFeature.java
src/test/java/com/kttdevelopment/mal4j/TestExperimentalEnabler.java

- Add `All` option for experimental features
- Optimize test case
[WF-3019280369](https://github.com/KatsuteDev/Mal4J/actions/runs/3019280369)
* Enable all experimental features using `MyAnimeList.enableExperimentalFeature(ExperimentalFeature.ALL)`

Added `All` option for experimental features

---

README.md
pom.xml
readme.bbcode
src/main/java/dev/katsute/mal4j/Fields.java
src/main/java/dev/katsute/mal4j/MyAnimeList.java
src/main/java/dev/katsute/mal4j/MyAnimeListAuthenticator.java
src/main/java/dev/katsute/mal4j/MyAnimeListImpl.java
src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Character.java
src/main/java/dev/katsute/mal4j/MyAnimeListService.java
src/main/java/dev/katsute/mal4j/Regex9.java
src/main/java/dev/katsute/mal4j/character/Animeography.java
src/main/java/dev/katsute/mal4j/character/Character.java
src/main/java/dev/katsute/mal4j/property/ExperimentalFeature.java
src/main/java11/module-info.java
src/main/java9/module-info.java
src/test/java/dev/katsute/mal4j/CharacterTests/TestCharacter.java
src/test/java/dev/katsute/mal4j/TestProvider.java
src/test/java/dev/katsute/mal4j/TestREADME.java
src/test/java/dev/katsute/mal4j/auth/TestAccessToken.java

- Add character
https://github.com/KatsuteDev/Mal4J/actions/runs/5040940621
This is an undocumented feature, you must use `MyAnimeList.enableExperimentalFeature(ExperimentalFeature.CHARACTERS)` to enable it.
Retrieve characters using `MyAnimeList.getCharacter(id)`.
Character information currently includes:
* Name
* Alternative names
* Picture
* Biography
* Animeography

Add character support

---

src/main/java/dev/katsute/mal4j/MyAnimeListImpl.java
src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Anime.java
src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Character.java
src/main/java/dev/katsute/mal4j/MyAnimeListSchema_Manga.java
src/test/java/dev/katsute/mal4j/AnimeTests/TestAnime.java
src/test/java/dev/katsute/mal4j/AnimeTests/TestAnimeSearch.java
src/test/java/dev/katsute/mal4j/CharacterTests/TestAnimeCharacter.java
src/test/java/dev/katsute/mal4j/CharacterTests/TestCharacter.java
src/test/java/dev/katsute/mal4j/MangaTests/TestManga.java
src/test/java/dev/katsute/mal4j/MangaTests/TestMangaSearch.java

- For Anime, Manga, character if any field is null, fetch full details and replace, only do this once
- Adjust method scopes for impl and schema
- Preview classes are still retained for backwards compatibility with v2, move all preview methods to top level in v4
https://github.com/KatsuteDev/Mal4J/actions/runs/5063811902
* Anime/Manga recommendation
* Related Anime/Manga

Fix incomplete Anime/Manga listings

---

.devcontainer/devcontainer.json
.github/workflows/mal_ci.yml
src/main/java/dev/katsute/mal4j/Logging.java
src/test/java/dev/katsute/mal4j/AnimeTests/TestUserAnimeListing.java
src/test/java/dev/katsute/mal4j/MangaTests/TestUserMangaListing.java

* devcontainer
* ci
https://github.com/KatsuteDev/Mal4J/actions/runs/6512299433

[DEV-1] Upgrade to Java 21

---

pom.xml
src/main/java/dev/katsute/mal4j/anime/property/AnimeType.java

*List any closed and/or relevant issues*
* Closes #420 
*List any changes made.*
* Adds missing fields `cm`, `pv`, and `tv_special`
https://github.com/KatsuteDev/Mal4J/actions/runs/7333329992
* `Commercial`
* `PromotionalVideo`
* `TVSpecial`

Add new Anime media types

---

.github/workflows/ci.yml
.github/workflows/dependabot.yml
.github/workflows/kdevbot.yml
.github/workflows/mal.yml
.github/workflows/release.yml
.github/workflows/stale.yml

This pull request includes an automated update from [Katsute/Manager](https://github.com/Katsute/Manager), authorized by [@KatsuteDev](https://github.com/KatsuteDev).
* `.github/workflows/stale.yml`
* `.github/workflows/dependabot.yml`
* No changes

Update repository files

---

pom.xml
src/main/java/dev/katsute/mal4j/property/RelationType.java
src/test/java/dev/katsute/mal4j/MangaTests/TestManga.java

*List any closed and/or relevant issues*
* Closes #462 
*List any changes made.*
* Add missing relation type adaptation

Add missing `RelationType` `Adaptation`
